/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/familyunit/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": FamilyUnitDto[];
                    "text/json": FamilyUnitDto[];
                    "application/*+json": FamilyUnitDto[];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": FamilyUnitDto;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/familyunit/{interested}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    interested: boolean | null;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": FamilyUnitDto[];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/familyunit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": FamilyUnitDto;
                    "text/json": FamilyUnitDto;
                    "application/*+json": FamilyUnitDto;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": FamilyUnitDto;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/familyunit/{rsvpCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    rsvpCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/familyunit/{rsvpCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    rsvpCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": FamilyUnitDto;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/helloworld": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIGatewayProxyResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/address-validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddressDto"];
                    "text/json": components["schemas"]["AddressDto"];
                    "application/*+json": components["schemas"]["AddressDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddressDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debugdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIGatewayProxyResponse: {
            /** Format: int32 */
            statusCode?: number;
            headers?: {
                [key: string]: string | null;
            } | null;
            multiValueHeaders?: {
                [key: string]: string[] | null;
            } | null;
            body?: string | null;
            isBase64Encoded?: boolean;
        };
        AddressDto: {
            streetAddress?: string | null;
            streetAddressAbbreviation?: string | null;
            secondaryAddress?: string | null;
            city?: string | null;
            cityAbbreviation?: string | null;
            state?: string | null;
            postalCode?: string | null;
            province?: string | null;
            zipCode?: string | null;
            zipPlus4?: string | null;
            urbanization?: string | null;
            country?: string | null;
            countryISOCode?: string | null;
        };
        /** @enum {string} */
        AgeGroupEnum: "Adult" | "Teenager" | "Child" | "Toddler" | "Baby";
        DeleteResponse: {
            success?: boolean;
        };
        FamilyUnitDto: {
            rsvpCode?: string | null;
            unitName?: string | null;
            tier?: string | null;
            guests?: GuestDto[] | null;
            mailingAddress?: string | null;
            additionalAddresses?: string[] | null;
            invitationResponseNotes?: string | null;
            /** Format: int32 */
            potentialHeadCount?: number;
            /** Format: date-time */
            familyUnitLastLogin?: string | null;
        };
        GuestDto: {
            rsvpCode?: string | null;
            guestId?: string | null;
            /** Format: int32 */
            guestNumber?: number | null;
            auth0Id?: string | null;
            firstName?: string | null;
            additionalFirstNames?: string[] | null;
            lastName?: string | null;
            roles?: components["schemas"]["RoleEnum"][] | null;
            email?: string | null;
            phone?: string | null;
            rsvp?: components["schemas"]["RsvpDto"];
            preferences?: components["schemas"]["PreferencesDto"];
            ageGroup?: components["schemas"]["AgeGroupEnum"];
            guestLogins?: string[] | null;
        };
        /** @enum {string} */
        InvitationResponseEnum: "Pending" | "Interested" | "Declined";
        /** @enum {string} */
        MealPreferenceEnum: "Omnivore" | "Vegetarian" | "Vegan";
        PreferencesDto: {
            guestId?: string | null;
            meal?: components["schemas"]["MealPreferenceEnum"];
            kidsPortion?: boolean | null;
            foodAllergies?: string | null;
            specialAlcoholRequests?: string | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** @enum {string} */
        RoleEnum: "Guest" | "Party" | "Rehearsal" | "Builder" | "Staff" | "Admin";
        RsvpDto: {
            guestId?: string | null;
            invitationResponse?: components["schemas"]["InvitationResponseEnum"];
            wedding?: components["schemas"]["RsvpEnum"];
            sleepPreference?: components["schemas"]["SleepPreferenceEnum"];
            rehearsalDinner?: components["schemas"]["RsvpEnum"];
            fourthOfJuly?: components["schemas"]["RsvpEnum"];
            buildWeek?: components["schemas"]["RsvpEnum"];
            /** Format: date-time */
            arrivalDate?: string | null;
            rsvpNotes?: string | null;
        };
        /** @enum {string} */
        RsvpEnum: "Pending" | "Attending" | "Declined";
        /** @enum {string} */
        SleepPreferenceEnum: "Unknown" | "Camping" | "Hotel";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
