/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/familyunit/createfamilyunits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": FamilyUnitDto[];
                    "text/json": FamilyUnitDto[];
                    "application/*+json": FamilyUnitDto[];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": FamilyUnitDto;
                        "application/json": FamilyUnitDto;
                        "text/json": FamilyUnitDto;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/FamilyUnit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    rsvpCode?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": FamilyUnitDto;
                        "application/json": FamilyUnitDto;
                        "text/json": FamilyUnitDto;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/HelloWorld": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["APIGatewayProxyResponse"];
                        "application/json": components["schemas"]["APIGatewayProxyResponse"];
                        "text/json": components["schemas"]["APIGatewayProxyResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIGatewayProxyResponse: {
            /** Format: int32 */
            statusCode?: number;
            headers?: {
                [key: string]: string | null;
            } | null;
            multiValueHeaders?: {
                [key: string]: string[] | null;
            } | null;
            body?: string | null;
            isBase64Encoded?: boolean;
        };
        /** @enum {string} */
        AgeGroupEnum: "Adult" | "Teenager" | "Child" | "Toddler" | "Baby";
        FamilyUnitDto: {
            rsvpCode?: string | null;
            unitName?: string | null;
            tier?: string | null;
            guests?: GuestDto[] | null;
            invitationResponse?: components["schemas"]["InvitationResponseEnum"];
            mailingAddress?: string | null;
            invitationResponseNotes?: string | null;
            /** Format: int32 */
            headCount?: number;
            /** Format: date-time */
            familyUnitLastLogin?: string | null;
        };
        GuestDto: {
            guestId?: string | null;
            auth0Id?: string | null;
            firstName?: string | null;
            lastName?: string | null;
            roles?: components["schemas"]["RoleEnum"][] | null;
            email?: string | null;
            phone?: string | null;
            rsvp: components["schemas"]["RsvpDto"];
            preferences?: components["schemas"]["PreferencesDto"];
            ageGroup?: components["schemas"]["AgeGroupEnum"];
            rsvpNotes?: string | null;
            /** Format: date-time */
            guestLastLogin?: string | null;
        };
        /** @enum {string} */
        InvitationResponseEnum: "Pending" | "Interested" | "Declined";
        /** @enum {string} */
        MealPreferenceEnum: "Omnivore" | "Vegetarian" | "Vegan";
        PreferencesDto: {
            guestId?: string | null;
            meal?: components["schemas"]["MealPreferenceEnum"];
            kidsPortion?: boolean;
            foodAllergies?: string | null;
            specialAlcoholRequests?: string | null;
        };
        /** @enum {string} */
        RoleEnum: "None" | "Party" | "Rehearsal" | "Builder" | "Staff" | "Admin";
        RsvpDto: {
            guestId?: string | null;
            invitation: components["schemas"]["InvitationResponseEnum"];
            wedding?: components["schemas"]["RsvpEnum"];
            sleepPreference?: components["schemas"]["SleepPreferenceEnum"];
            rehearsalDinner?: components["schemas"]["RsvpEnum"];
            fourthOfJuly?: components["schemas"]["RsvpEnum"];
            buildWeek?: components["schemas"]["RsvpEnum"];
            /** Format: date-time */
            arrivalDate?: string;
        };
        /** @enum {string} */
        RsvpEnum: "Pending" | "Attending" | "Declined";
        /** @enum {string} */
        SleepPreferenceEnum: "Unknown" | "Camping" | "Hotel";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
