import {FamilyUnitDto, InvitationResponseEnum} from '@/types/api';

export const mockFamilyUnitDto: FamilyUnitDto = {
  'invitationCode': 'abc',
  'unitName': 'Stubler-Sikorra Family',
  'tier': 'Gold',
  'potentialHeadCount': 4,
  'familyUnitLastLogin': '2024-04-25T10:30:00Z',
  'guests': [
    {
      'invitationCode': 'abc',
      'guestId': 'guest-001',
      'guestNumber': 1,
      'auth0Id': 'auth0|1234567890abcdef',
      'firstName': 'Steph',
      'additionalFirstNames': [
        'Marie',
      ],
      'lastName': 'Stubler',
      'roles': [
        'Guest',
      ],
      'email': 'steph.stubler@example.com',
      'emailVerified': true,
      'phone': '+1-555-123-4567',
      'ageGroup': 'Adult',
      'rsvp': {
        'guestId': 'guest-001',
        'invitationResponse': InvitationResponseEnum.Interested,
        'wedding': 'Attending',
        'sleepPreference': 'Hotel',
        'rehearsalDinner': 'Pending',
        'fourthOfJuly': 'Declined',
        'buildWeek': 'Pending',
        'arrivalDate': '2024-05-01T15:00:00Z',
        'rsvpNotes': 'Looking forward to the event!',
      },
      'preferences': {
        'guestId': 'guest-001',
        'meal': 'Vegetarian',
        'kidsPortion': false,
        'foodAllergies': 'None',
        'specialAlcoholRequests': 'No preferences',
      },
      'guestLogins': [
        'login1',
        'login2',
      ],
    },
    {
      'invitationCode': 'abc',
      'guestId': 'guest-002',
      'guestNumber': 2,
      'auth0Id': 'auth0|abcdef1234567890',
      'firstName': 'Topher',
      'additionalFirstNames': [
        'James',
      ],
      'lastName': 'Sikorra',
      'roles': [
        'Guest',
      ],
      'email': 'topher.sikorra@example.com',
      'emailVerified': false,
      'phone': '+1-555-987-6543',
      'ageGroup': 'Teenager',
      'rsvp': {
        'guestId': 'guest-002',
        'invitationResponse': InvitationResponseEnum.Pending,
        'wedding': 'Pending',
        'sleepPreference': 'Unknown',
        'rehearsalDinner': 'Pending',
        'fourthOfJuly': 'Pending',
        'buildWeek': 'Pending',
        'arrivalDate': null,
        'rsvpNotes': 'Awaiting confirmation from parents.',
      },
      'preferences': {
        'guestId': 'guest-002',
        'meal': 'Omnivore',
        'kidsPortion': true,
        'foodAllergies': 'Peanuts',
        'specialAlcoholRequests': null,
      },
      'guestLogins': [],
    },
  ],
  'mailingAddress': '123 Main St, Springfield, IL 62704',
  'additionalAddresses': [
    '456 Elm St, Springfield, IL 62705',
    '789 Oak St, Springfield, IL 62706',
  ],
  'invitationResponseNotes': 'Family is excited to attend!',
} as FamilyUnitDto;
